routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('admin/user', 'UserController@index');
Route::put('regPat/{PatientId}', 'regPatientsController@change')->name('change');
Route::resource('regPat', 'regPatientsController',['names'=>[
    'create'=>'regCreate',
    'edit'=>'regEdit',
]]);
Route::get('check/summary', 'precheckController@summary')->name('summary');
Route::resource('check', 'precheckController');
Route::get('diagnosis/cleared', 'treatmentController@cleared')->name('cleared');
Route::resource('diagnosis', 'treatmentController');
Route::get('labResults/summary', 'labResultsController@summary')->name('summary');
Route::resource('labResults', 'labResultsController');
Route::resource('insure', 'insurancesController');
Route::resource('dawa', 'medController');
Route::get('drugs/payments/details', 'medicationController@details')->name('details');
Route::get('drugs/payments/payscript', 'medicationController@payscript')->name('payscript');
Route::put('drugs/payments/{paymentId}', 'medicationController@processpay')->name('drugs.payments.processpay');
Route::get('drugs/payments/{paymentId}/payment', 'medicationController@payment')->name('payment');
Route::resource('drugs', 'medicationController');
//Route::post('drugs/fetch', 'medicationController@fetch')->name('dynamicdependent.fetch');
//Route::post('drugs/{drug}/edit/fetch', 'medicationController@fetch')->name('dynamicdependent.fetch');
//Route::post('drugs/fetch', 'medicationController@fetch')->name('dynamicdependent.fetch');
Route::get('verify/{token}', 'VerifyController@verify')->name('verify');
Route::get('/regPat/create/action', 'regPatientsController@action')->name('regPat/create.action');
Route::group(['middleware' => ['isVerified']], function () {
    // …
});
Route::get('email-verification/error', 'Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'Auth\RegisterController@getVerification')->name('email-verification.check');

resources/views/dawa/create.blade.php
@extends('adminlte::page')

@section('content')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/css/auth.css') }}">
    <style>
        * {
            box-sizing: border-box;
        }
        .column {
            float: left;
            width: 50%;
            padding: 10px;
            height: auto; /* Should be removed. Only for demonstration */
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
            }
        }
    </style>
    {!! Form::open(['action' => 'medController@store', 'method' => 'POST']) !!}
    <div class="container" align="center">
        <blockquote><h2>DRUG DETAILS</h2></blockquote>
        <div class="register-box-body row" style="width: 60%; height: auto; background-color: #e3e8ef;">

            {!! csrf_field() !!}

            <div class="form-group has-feedback {{ $errors->has('name') ? 'has-error' : '' }}">
                <b>Name:</b>
                <input type="text" name="name" class="form-control"
                       placeholder="{{ trans('adminlte::adminlte.full_name') }}">
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('quant') ? 'has-error' : '' }}">
                <b>Quantity:</b>
                <input type="number" name="quant" required class="form-control"
                       placeholder="Quantity">
                @if ($errors->has('quant'))
                    <span class="help-block">
                        <strong>{{ $errors->first('quant') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('price') ? 'has-error' : '' }}">
                <b>Price:</b>
                <input type="number" name="price" class="form-control" required placeholder="Price">
                @if ($errors->has('price'))
                    <span class="help-block">
                        <strong>{{ $errors->first('price') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('mfBy') ? 'has-error' : '' }}">
                <b>Manufacturer:</b>
                <input type="text" pattern="[A-Z a-z]*" name="mfBy" class="form-control"
                       placeholder="{{ trans('adminlte::adminlte.full_name') }}">
                @if ($errors->has('mfBy'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mfBy') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('mfdate') ? 'has-error' : '' }}">
                <b>Manufactured Date</b>
                <input type="date" name="mfdate" value="{{ old('mfdate') }}" class="form-control">
                @if ($errors->has('mfdate'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mfdate') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('expdate') ? 'has-error' : '' }}">
                <b>Expiring Date</b>
                <input type="date" name="expdate" value="{{ old('expdate') }}" class="form-control">
                @if ($errors->has('expdate'))
                    <span class="help-block">
                        <strong>{{ $errors->first('expdate') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <!-- /.form-box -->
    </div><!-- /.register-box -->
    <div align="center">
        <button type="submit" class="btn btn-primary"><b>SAVE</b></button>
    </div>
    {!! Form::close() !!}

@stop

resources/views/dawa/edit.blade.php
@extends('adminlte::page')

@section('content')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/css/auth.css') }}">
    <style>
        * {
            box-sizing: border-box;
        }
        .column {
            float: left;
            width: 50%;
            padding: 10px;
            height: auto; /* Should be removed. Only for demonstration */
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
            }
        }
    </style>
    {!! Form::open(['action' => ['medController@update', $edit_med->med_id], 'method' => 'POST']) !!}
    <div class="container" align="center" style="margin-top: -4%">
        <blockquote><h2>DRUG DETAILS</h2></blockquote>
        <div class="register-box-body row" align="left" style="width: 40%; margin-top: -3%; height: auto; background-color: #e3e8ef;">

            {!! csrf_field() !!}

            <div class="form-group has-feedback {{ $errors->has('name') ? 'has-error' : '' }}">
                <b>Name:</b>
                <input type="text" pattern="[A-Z a-z]*" value="{{ $edit_med->med_name }}" name="name" class="form-control"
                       placeholder="{{ trans('adminlte::adminlte.full_name') }}">
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('quant') ? 'has-error' : '' }}">
                <b>Quantity:</b>
                <input type="number" value="{{ $edit_med->quantity }}" name="quant" class="form-control"
                       placeholder="Quantity">
                @if ($errors->has('quant'))
                    <span class="help-block">
                        <strong>{{ $errors->first('quant') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('price') ? 'has-error' : '' }}">
                <b>Price:</b>
                <input type="number" name="price" value="{{ $edit_med->price }}" class="form-control" placeholder="Price">
                @if ($errors->has('price'))
                    <span class="help-block">
                        <strong>{{ $errors->first('price') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('mfBy') ? 'has-error' : '' }}">
                <b>Manufacturer:</b>
                <input type="text" pattern="[A-Z a-z]*" name="mfBy" value="{{ $edit_med->manufacturedBy }}" class="form-control"
                       placeholder="{{ trans('adminlte::adminlte.full_name') }}">
                @if ($errors->has('mfBy'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mfBy') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('mfdate') ? 'has-error' : '' }}">
                <b>Manufactured Date</b>
                <input type="date" name="mfdate" value="{{ $edit_med->mfDate }}" class="form-control">
                @if ($errors->has('mfdate'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mfdate') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('expdate') ? 'has-error' : '' }}">
                <b>Expiring Date</b>
                <input type="date" name="expdate" value="{{ $edit_med->expiry_date }}" class="form-control">
                @if ($errors->has('expdate'))
                    <span class="help-block">
                        <strong>{{ $errors->first('expdate') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <!-- /.form-box -->
    </div><!-- /.register-box -->
    <div align="center">
        <button type="submit" class="btn btn-primary"><b>SAVE</b></button>
    </div>
    {{Form::hidden('_method', 'PUT')}}
    {!! Form::close() !!}

@stop

resources/views/dawa/index.blade.php
@extends('adminlte::page')
@section('content')
    <div class="container" style="margin-top: -4%">
        <h1>DRUGS</h1>
        <p><a href="{{ route('dawa.create') }}">Add Medicine</a> </p>
        <div class="table-responsive col-lg-10">
            @if(count($dawa) > 0)
                <table class="data-table" cellspacing="0" width="80%">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Manufacturer</th>
                        <th>MF Date</th>
                        <th>Exp Date</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($dawa as $item)
                        <tr>
                            <td>{{$item->med_id}}</td>
                            <td>{{$item->med_name}}</td>
                            <td>{{$item->quantity}}</td>
                            <td>{{$item->manufacturedBy}}</td>
                            <td>{{$item->mfDate}}</td>
                            <td>{{$item->expiry_date}}</td>
                            <td>
                                <!--<img src="storage/icon/del.png" height="20px" width="20px">
                                <img src="storage/icon/edit.png" height="20px" width="20px">-->
                            @if(!Auth::guest())
                                @if(Auth::user()->id == $item->pharEmpId && Auth::user()->role == "phar" && $current_time < $item->del_avTime) <!-- U can also specify e.g == 1 being userType-->

                                    {!!Form::open(['action' => ['medController@destroy', $item->med_id], 'method'=>'POST', 'class' => 'pull-right'])!!}
                                    {{Form::hidden('_method', 'DELETE')}}
                                    <button class="btn btn-default" onclick="return confirm('Are you sure you want to delete: {{ $item->med_name }}?')" type="submit"><img src="storage/icon/del.png" height="20px" width="20px"></button>
                                    {!!Form::close() !!}

                                    <a href="/dawa/{{$item->med_id}}/edit" style="margin-left: 26%">
                                        <img src="storage/icon/edit.png" height="20px" width="20px" onclick="return confirm('Edit  {{ $item->med_name }} medicine?')"></a>

                                    @endif
                                @if($current_time > $item->del_avTime && Auth::user()->role == "phar")
                                        <a href="/dawa/{{$item->med_id}}" style="margin-left: 26%">
                                            <img src="storage/icon/show.png" height="20px" width="20px">
                                        </a>
                                    @endif
                                    @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>
@stop
@section('js')
    <script>
        $(document).ready(function () {
            $('.data-table').dataTable();
        });
    </script>
@stop

resources/views/dawa/show.blade.php
@extends('adminlte::page')

@section('content')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/css/auth.css') }}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <!--script src="https://cdn.ckeditor.com/4.10.1/standard/ckeditor.js"></script-->
    <style>
        * {
            box-sizing: border-box;
        }
        .column {
            float: left;
            width: 50%;
            padding: 10px;
            height: auto; /* Should be removed. Only for demonstration */
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
            }
        }
    </style>

    <div class="container" align="center">
        <h2></h2>
        <div class="register-box box" style="width: 80%; margin: -4%; height: auto; background-color: #d4d6d8;">

            {!! csrf_field() !!}
            <div class="form-group has-feedback" style="width: 80%; margin: -3%;">
                <div row = "2" style="font-weight: bold; font-size: 1.5em">
                    <br />
                    <u>med</u><br />
                </div>
                <div class="column" align="left" style="font-weight: bold">
                    HEIGHT          : <br />
                    WEIGHT          : <br />
                    TEMPERATURE     : <br />
                </div>

                <div class="column" align="left" style="font-weight: bold">
                    PULSE RATE      : <br />
                    BLOOD PRESSURE  : <br />
                    BMI             :

                    <br />
                </div>
            </div>
        </div>
        <!-- /.form-box -->
    </div><!-- /.register-box -->
    <a href="/dawa/{{$getdata->med_id}}/edit" style="margin-left: 26%">
        <img src="storage/icon/edit.png" height="20px" width="20px">
    </a>
    <script>
        $(document).ready(function () {
            $('#first_one').multiselect({
                nonSelectedText:'Type Medicine Name',
                buttonWidth:'80%'
            });
        });
    </script>

@stop